#pragma once

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define LAUNCHER_VERSION_MAJOR 1
#define LAUNCHER_VERSION_MINOR 3
#define LAUNCHER_VERSION_PATCH 0
#define LAUNCHER_VERSION TOSTRING(LAUNCHER_VERSION_MAJOR) "." TOSTRING(LAUNCHER_VERSION_MINOR) "." TOSTRING(LAUNCHER_VERSION_PATCH)
